### ISSUE TITLE
Install Watir on my VM uslznbockrath

### ISSUE THREAD

**Issue by NathanBockrath** [Traap/tool-validation#50]

**Comment by NathanBockrath** [comment]
`$ ruby test1.rb
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/watir-6.10.3/lib/watir/elements/element.rb:623:in `raise_present': element located, but timed out after 30 seconds, waiting for #<Watir::Button: located: true; {:type=>"submit", :tag_name=>"button"}> to be present (Watir::Exception::UnknownObjectException)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/watir-6.10.3/lib/watir/elements/element.rb:668:in `rescue in element_call'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/watir-6.10.3/lib/watir/elements/element.rb:657:in `element_call'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/watir-6.10.3/lib/watir/elements/element.rb:125:in `click'
        from test1.rb:7:in `<main>'

`

**Comment by NathanBockrath** [comment]
So, the google home page no longer includes a "submit" button;  I'll need to implement some form of sending a return key to get the results.

**Comment by NathanBockrath** [comment]
The code which does not generate an error:
'''
require 'watir'

browser = Watir::Browser.new :chrome

browser.goto 'google.com'
browser.text_field(title: 'Search').wait_until(&:present?).set 'Hello World!\n'



# browser.button(type: 'submit').click

puts browser.title
# => 'Hello World! - Google Search'
browser.quit
'''
Moving on...
